# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
target 'SwiftWeiBo' do
# Uncomment this line if you're using Swift
use_frameworks!

pod 'AFNetworking'
pod 'SDWebImage'
pod 'SnapKit', '~> 3.0.2'
pod 'SVProgressHUD'
pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git" 
pod "MJRefresh"

end
